//aula 116 - consumir API
// GET - 
// POST - FAZ INSERÇÃO
// PUT - FAZ UMA ATUALIZAÇÃO
// DELETE - DELETAR
// UPDATE - 
// PATCH - FAZ UMA ATUALIZAÇÃO

//COLOQUEI O DARTION PUB DEV
//CRIEI UMA PASTA CHAMADA BACKEND
//ACESSAR PASTA E DAR O COMANDO DARTION INIT
// DEPOIS DE MANIPULAR SEUS DADOS JSON, VAMOS SUBIR PARA O SERVIDOR
// NA PASTA DARTION BACKEND, DE O SEGUINTE COMANDO
//DARTION SERVER